spring:
  application:
    name: wedding-invite

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://dpg-d2vk878dl3ps7399fkhg-a.oregon-postgres.render.com/rsvp_6yer
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rsvp}?useEncoding=true&characterEncoding=UTF-8
    hikari:
      username: ${DB_USER_NAME:bost}
      password: ${DB_PASSWORD:S2gIiqs9P0hbMkmG22oCN45SbF8fAul2}
      driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:2714}

wedding:
  invitation:
    base-url: ${INVITE_URL:https://wedding-invite-zxks.onrender.com}
    card:
      template-path: ./templates
      output-path: ./generated-cards
    venue:
      max-guests: 100
      seats-per-table: 10

logging:
  level:
    com.wedding.invitation: DEBUG
